Repository woowa-techcamp-2022/android-banchan-01, pull requests merged in 2022-08, with the labels that each got.

#2 [CHORE] Dependency 세팅 + BaseClass 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/woowahan_banchan/application/BanchanApplication.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/MainActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/base/BaseActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/base/BaseFragment.kt
  app/src/main/res/layout/activity_main.xml
  build.gradle
Labels: chore 🏗, Iceman 🧊, Skipancho 🌮

#3 [CHORE] Dependency 추가(retrofit, okhttp) + Permission 추가 (Internet)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  build.gradle
Labels: chore 🏗, Iceman 🧊, Skipancho 🌮

#5 [FEATURE] Database 초기 구현 - Local Dto 추가
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/BanchanDatabase.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/local/CartDto.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/local/HistoryDto.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/local/OrderDto.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/local/OrderItemDto.kt
Labels: feature 🚀, Iceman 🧊, Skipancho 🌮

#8 [FEATURE] Local Database API Dao 인터페이스 + Dto 데이터 클래스 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/woowahan_banchan/data/database/BanchanDatabase.kt
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/CartDao.kt
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/HistoryDao.kt
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderDao.kt
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderItemDao.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/BanchanDatabase.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/local/CartDto.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/local/HistoryDto.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/local/OrderDto.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/local/OrderItemDto.kt
Labels: feature 🚀, Iceman 🧊, Skipancho 🌮

#9 [FEATURE] Remote Api Service 인터페이스 + Response 데이터 클래스 구현
  app/src/main/java/co/kr/woowahan_banchan/data/api/BestService.kt
  app/src/main/java/co/kr/woowahan_banchan/data/api/DetailService.kt
  app/src/main/java/co/kr/woowahan_banchan/data/api/MainDishService.kt
  app/src/main/java/co/kr/woowahan_banchan/data/api/SideDishService.kt
  app/src/main/java/co/kr/woowahan_banchan/data/api/SoupDishService.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/ApiResponse.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/BestResponse.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DetailDataResponse.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DetailResponse.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DishResponse.kt
Labels: feature 🚀, Iceman 🧊, Skipancho 🌮

#12 [FEATURE] CoroutineModule 구현
  app/src/main/java/co/kr/woowahan_banchan/di/CoroutineModule.kt
Labels: feature 🚀, Pair Programming 🤝

#13 [FEATURE] Remote DataSource 구현 + ApiModule 구현
  app/build.gradle
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/best/BestDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/best/BestDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/detail/DetailDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/detail/DetailDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/maindish/MainDishDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/maindish/MainDishDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/sidedish/SideDishDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/sidedish/SideDishDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/soupdish/SoupDishDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/soupdish/SoupDishDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/di/ApiModule.kt
Labels: feature 🚀, Pair Programming 🤝

#14 [FEATURE] Local DataSource 구현
  app/src/main/java/co/kr/woowahan_banchan/data/database/BanchanDatabase.kt
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/CartDao.kt
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/HistoryDao.kt
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderDao.kt
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderItemDao.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/local/CartDto.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/local/HistoryDto.kt
  app/src/main/java/co/kr/woowahan_banchan/di/DataSourceModule.kt
  app/src/main/java/co/kr/woowahan_banchan/di/DatabaseModule.kt
Labels: feature 🚀, Pair Programming 🤝

#16 [FEATURE] RemoteDataSourceModule 구현
  app/src/main/java/co/kr/woowahan_banchan/di/DataSourceModule.kt
Labels: feature 🚀, Pair Programming 🤝

#17 [FEATURE] DishRepository 내 BestDataSource 연결
  app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DishResponse.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/di/DataSourceModule.kt
  app/src/main/java/co/kr/woowahan_banchan/di/RepositoryModule.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/dish/BestItem.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/dish/Dish.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/DishRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: feature 🚀, Pair Programming 🤝

#19 [FEATURE] HistoryRepository 구현
  app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DetailDataResponse.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/di/RepositoryModule.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/history/HistoryItem.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/HistoryRepository.kt
Labels: feature 🚀, Iceman 🧊

#20 [FEATURE] getDishes 메소드 구현
  app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/di/RepositoryModule.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/DishRepository.kt
Labels: feature 🚀, Skipancho 🌮

#23 [FEATURE] 최근 내역 조회 미리보기(최대 7개 표시) 메서드 구현
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/HistoryDao.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt
Labels: feature 🚀, Iceman 🧊

#24 [FEATURE] 색상 및 아이콘 추가
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_cart.xml
  app/src/main/res/drawable/ic_cart_action.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_checkbox_checked.xml
  app/src/main/res/drawable/ic_checkbox_empty.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_down.xml
  app/src/main/res/drawable/ic_grid.xml
  app/src/main/res/drawable/ic_linear.xml
  app/src/main/res/drawable/ic_reload.xml
  app/src/main/res/drawable/ic_right_arrow.xml
  app/src/main/res/drawable/ic_user.xml
  app/src/main/res/drawable/ic_user_badge.xml
  app/src/main/res/values/colors.xml
Labels: feature 🚀, Skipancho 🌮

#25 [FEATURE] DetailRepository 구현
  app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DetailDataResponse.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/DetailRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/di/RepositoryModule.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/detail/DishInfo.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/DetailRepository.kt
Labels: feature 🚀, Iceman 🧊

#28 [FEATURE] OrderDao, OrderItemDao 수정
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderDao.kt
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderItemDao.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSourceImpl.kt
Labels: feature 🚀, Iceman 🧊

#29 [FEATURE] OrderHistoryRepository 구현
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderItemDao.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/local/OrderDto.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/local/OrderItemDto.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/di/RepositoryModule.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/orderhistory/OrderHistory.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/orderhistory/OrderItem.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/OrderHistoryRepository.kt
Labels: feature 🚀, Iceman 🧊

#31 [FEATURE] ImageLoader 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/woowahan_banchan/util/ImageLoader.kt
Labels: feature 🚀, Skipancho 🌮

#32 [MOVE] presentation 패키지 구조화
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/base/BaseActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/base/BaseFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: feature 🚀, Pair Programming 🤝

#34 [CHORE] color, theme 수정
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: chore 🏗, Iceman 🧊

#36 [FEATURE] 9_Product_Detail 화면 관련 color, theme, drawable 추가
  app/src/main/res/drawable/bg_default_tab.xml
  app/src/main/res/drawable/bg_loading_dialog.xml
  app/src/main/res/drawable/bg_selected_tab.xml
  app/src/main/res/drawable/circle.xml
  app/src/main/res/drawable/ic_minus.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/selector_product_detail_indicator.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: feature 🚀, Iceman 🧊

#35 [FEATURE] Home 화면 관련 UseCase 및 Adapter 구현
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/dish/Dish.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetBestsUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/BestItemAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/DishAdapter.kt
  app/src/main/res/drawable/rectangle_radius_999.xml
  app/src/main/res/layout/item_best.xml
  app/src/main/res/layout/item_dish.xml
Labels: feature 🚀, Skipancho 🌮

#37 [FEATURE] 9_Product Detail 화면 관련 domain, data, util 파일 구현 및 수정
  app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DetailDataResponse.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/detail/DishInfo.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/ProductDetailUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/util/ContextUtil.kt
  app/src/main/java/co/kr/woowahan_banchan/util/IntExtension.kt
Labels: feature 🚀, Iceman 🧊

#38 [FEATURE] 9_Product Detail 화면 presentation
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/ProductDetailViewPagerAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/LoadingDialog.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
  app/src/main/res/drawable/strike_through.xml
  app/src/main/res/layout/activity_product_detail.xml
  app/src/main/res/layout/dialog_loading.xml
  app/src/main/res/layout/item_product_detail.xml
Labels: feature 🚀, Iceman 🧊

#39 [FEATURE] 1_Home 화면 UI 구현
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/dish/Dish.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/BestItemAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/DishAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/ViewPagerAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
  app/src/main/res/drawable/ic_cart_btn.xml
  app/src/main/res/drawable/ic_cart_btn_added.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_best.xml
  app/src/main/res/layout/fragment_maindish.xml
  app/src/main/res/layout/item_best.xml
  app/src/main/res/layout/item_dish.xml
  app/src/main/res/menu/menu_app_bar.xml
Labels: feature 🚀, Skipancho 🌮

#41 [FEATURE] BestFragment-ProductDetailActivity 연결
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
Labels: feature 🚀, Iceman 🧊

#43 [FEATURE] 기존 DishRepository에 있던 장바구니에 담는 기능을 CartRepository를 새로 생성해 이전
  app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/di/RepositoryModule.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/CartRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/DishRepository.kt
Labels: feature 🚀, Iceman 🧊

#45 [FEATURE] 장바구니 추가 기능 구현
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/CartDao.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/CartAddUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
Labels: feature 🚀, Iceman 🧊

#46 [REFACTOR] 코드 리뷰 반영 - ImageLoader , BestFragment
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/util/ImageLoader.kt
Labels: refactor 🛠, Skipancho 🌮

#48 [FEATURE] 장바구니 추가 성공 시 표시되는 Dialog 구현
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddDialog.kt
  app/src/main/res/drawable/bg_alert_dialog.xml
  app/src/main/res/drawable/inset_horizontal_24.xml
  app/src/main/res/layout/dialog_cart_add.xml
Labels: feature 🚀, Iceman 🧊

#50 [FEATURE] OrderListFragment UI initView() 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/OrderActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderlist/OrderListFragment.kt
  app/src/main/res/layout/activity_order.xml
  app/src/main/res/layout/fragment_order_list.xml
  app/src/main/res/layout/item_order_list.xml
Labels: feature 🚀, Iceman 🧊

#51 [FEATURE] OrderListFragment-주문내역 조회 API 연결
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderDao.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderListUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/OrderActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderlist/OrderListFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/UiState.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderListViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/util/IntExtension.kt
  app/src/main/java/co/kr/woowahan_banchan/util/NumberExtension.kt
  app/src/main/res/layout/fragment_order_list.xml
  app/src/main/res/layout/item_order_list.xml
  app/src/main/res/values/colors.xml
Labels: feature 🚀, Iceman 🧊

#52 [FEATURE] 2_Maindish 화면 관련 UseCase 및 Adapter 구현
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetDishesUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/BestItemAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/DishAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/FilterSpinnerAdapter.kt
  app/src/main/res/layout/item_best.xml
  app/src/main/res/layout/item_dish_grid.xml
  app/src/main/res/layout/item_dish_linear.xml
  app/src/main/res/layout/item_filter.xml
Labels: feature 🚀, Skipancho 🌮

#55 [REFACTOR] UiState통일 + BestViewModel 분리
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/BestViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/MainDishViewModel.kt
  app/src/main/res/layout/fragment_main_dish.xml
Labels: refactor 🛠, Skipancho 🌮

#57 [FEATURE] OrderListFragment RecyclerView ItemDecoration 적용
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/OrderActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderlist/OrderListFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/util/NumberExtension.kt
  app/src/main/java/co/kr/woowahan_banchan/util/OrderListItemDecoration.kt
  app/src/main/res/layout/item_order_list.xml
Labels: feature 🚀, Iceman 🧊

#59 [FEATURE] ExtraExtension, ArgumentExtension 추가
  app/src/main/java/co/kr/woowahan_banchan/presentation/decoration/OrderListItemDecoration.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderlist/OrderListFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/util/ArgumentExtension.kt
  app/src/main/java/co/kr/woowahan_banchan/util/ExtraExtension.kt
  app/src/main/res/values/colors.xml
Labels: feature 🚀, Iceman 🧊

#60 [FEATURE] 12_OrderDetail 화면 기초 기능 구현
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderDetailUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/OrderActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderlist/OrderListFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderDetailViewModel.kt
  app/src/main/res/layout/fragment_order_detail.xml
  app/src/main/res/layout/item_order_detail.xml
  app/src/main/res/values/colors.xml
Labels: feature 🚀, Iceman 🧊

#63 [FEATURE] 4_Side 화면 구현
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/ViewPagerAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/sidedish/SideDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/OtherDishViewModel.kt
  app/src/main/res/layout/fragment_other_dish.xml
  app/src/main/res/layout/fragment_side_dish.xml
Labels: feature 🚀, Skipancho 🌮

#67 [FEATURE] BottomSheet UI 구현
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddBottomSheet.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/bottomsheet/BottomSheetViewModel.kt
  app/src/main/res/layout/dialog_cart_add_bottom.xml
  app/src/main/res/values/themes.xml
Labels: feature 🚀, Skipancho 🌮

#64 [FEATURE] 12_OrderDetail 화면 구현
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderDao.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/OrderHistoryRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderTimeUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderDetailViewModel.kt
Labels: feature 🚀, Iceman 🧊

#68 [FEATURE] BottomSheet 이벤트 적용
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/BestItemAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/DishAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddBottomSheet.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/bottomsheet/BottomSheetViewModel.kt
  app/src/main/res/layout/dialog_cart_add_bottom.xml
Labels: feature 🚀, Skipancho 🌮

#70 [FEATURE] 장바구니 아이콘에 Badge 추가
  app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/CartRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetCartItemCountUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
Labels: feature 🚀, Skipancho 🌮

#72 [REFACTOR] 1_Home 화면 수정
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetBestsUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/BestItemAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/decoration/HorizontalItemDecoration.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/decoration/HorizontalLayoutManager.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/listener/TouchInterceptorListener.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
  app/src/main/res/layout/fragment_best.xml
  app/src/main/res/layout/item_best.xml
  app/src/main/res/layout/item_best_header.xml
Labels: refactor 🛠, Skipancho 🌮

#74 [REFACTOR] #73 - 텍스트 위아래 정렬 맞추기
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/OrderActivity.kt
  app/src/main/res/layout/item_order_list.xml
Labels: refactor 🛠, Iceman 🧊

#76 [FEATURE] ProductDetailActivity에서 조회한 메뉴를 History 테이블에 저장
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/HistoryRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/HistoryAddUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
Labels: feature 🚀, Iceman 🧊

#77 [FEATURE] 16_RecentlyViewedProducts 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DetailDataResponse.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/RecentlyViewedUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/RecentlyViewedAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/recentlyviewed/RecentlyViewedFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/RecentlyViewedViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/util/NumberExtension.kt
  app/src/main/res/layout/activity_cart.xml
  app/src/main/res/layout/fragment_recently_viewed.xml
  app/src/main/res/layout/item_recently_viewed.xml
Labels: feature 🚀, Iceman 🧊

#79 [FEATURE] RecentlyViewedFragment RecyclerView ItemDecoration 적용
  app/src/main/java/co/kr/woowahan_banchan/presentation/decoration/GridItemDecoration.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/recentlyviewed/RecentlyViewedFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt
  app/src/main/res/layout/fragment_recently_viewed.xml
Labels: feature 🚀, Iceman 🧊

#80 [FEATURE] RecentlyViewedFragment RecyclerView Item Click Event 처리
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/history/HistoryItem.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/RecentlyViewedAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/recentlyviewed/RecentlyViewedFragment.kt
Labels: feature 🚀, Iceman 🧊

#83 [REFACTOR] BottomSheetDialog용 데이터 타입 분리
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/dish/SelectedDish.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/history/HistoryItem.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/recentlyviewed/RecentlyViewedFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddBottomSheet.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/bottomsheet/BottomSheetViewModel.kt
Labels: refactor 🛠, Skipancho 🌮

#84 [FEATURE] 홈 화면 상단 프로필 아이콘에 현재 배송중인 상품이 있는 경우 아이콘 변경
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderDao.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/OrderHistoryRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/LatestOrderTimeUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/UiState.kt
Labels: feature 🚀, Iceman 🧊

#87 [FEATURE] Android 12 이상에서 Splash Screen 구현
  app/build.gradle
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values-v31/themes.xml
Labels: feature 🚀, Iceman 🧊

#88 [FEATURE] 11_Cart 화면 UI 구현
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/cart/CartItem.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/CartAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
  app/src/main/res/drawable/ic_minus_12.xml
  app/src/main/res/drawable/ic_plus_12.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/item_cart.xml
  app/src/main/res/layout/layout_cart_info.xml
  app/src/main/res/layout/layout_cart_recently_viewed.xml
Labels: feature 🚀, Skipancho 🌮

#90 [FIX] 최근 주문 내역의 주문시간 조회 API 수정
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
Labels: bug 🐛, Iceman 🧊

#91 [FEATURE] 장바구니 관련 UseCase 추가
  app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DetailDataResponse.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/di/RepositoryModule.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/CartRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/DeleteCartItemsUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetCartItemsUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/UpdateCartItemsUseCase.kt
Labels: feature 🚀, Skipancho 🌮

#93 [FEATURE] API 30 이하 SplashScreen 적용
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/themes.xml
Labels: feature 🚀, Iceman 🧊

#95 [FEATURE] themes.xml DayNight -> Light로 변경
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: feature 🚀, Iceman 🧊

#97 [FEATURE] 11_Cart 화면 버튼 이벤트 및 주문하기 구현
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/cart/CartItem.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/CartAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
  app/src/main/res/drawable/selector_btn_bg.xml
  app/src/main/res/drawable/strike_through.xml
  app/src/main/res/layout/fragment_cart.xml
  app/src/main/res/layout/item_cart.xml
  app/src/main/res/layout/layout_cart_info.xml
  app/src/main/res/layout/layout_cart_recently_viewed.xml
Labels: feature 🚀, Skipancho 🌮

#98 [FEATURE] 장바구니에서 변화가 있는 아이템만 데이터베이스에 업데이트 하도록 수정
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/UpdateCartItemsUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/CartAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/RecentlyViewedAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddDialog.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
Labels: feature 🚀, Skipancho 🌮

#100 [FEATURE] NumberPickerDialog 구현 및 적용
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/CartAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/NumberPickerDialog.kt
  app/src/main/res/layout/dialog_number_picker.xml
Labels: feature 🚀, Skipancho 🌮

#103 [FEATURE] 주문 20분 후 Notification 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/woowahan_banchan/presentation/notification/AlarmReceiver.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderDetailViewModel.kt
Labels: feature 🚀, Iceman 🧊

#104 [FEATURE] 장바구니 아이템 선택 삭제 기능 구현
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/CartAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
  app/src/main/res/layout/fragment_best.xml
  app/src/main/res/layout/fragment_cart.xml
Labels: feature 🚀, Skipancho 🌮

#107 [FEATURE] Spinner 화살표 전환 구현
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/FilterSpinner.kt
  app/src/main/res/drawable/bg_spinner_openned.xml
  app/src/main/res/layout/fragment_main_dish.xml
  app/src/main/res/layout/fragment_other_dish.xml
Labels: feature 🚀, Skipancho 🌮

#109 [FEATURE] sealed class ErrorEntity 정의
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/error/ErrorEntity.kt
Labels: feature 🚀, Iceman 🧊

#113 [REFACTOR] job을 반환하는 함수 제거 + View에서 domain Import 제거
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/dish/Dish.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/history/HistoryItem.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/BestItemAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/CartAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/DishAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/ViewPagerAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/recentlyviewed/RecentlyViewedFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/BestViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/MainDishViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/OtherDishViewModel.kt
Labels: refactor 🛠, Skipancho 🌮

#117 Feature/#105 error propagation
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/extension/RunCatchingErrorEntity.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/classifier/ErrorClassifier.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/error/ErrorEntity.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/result/CustomResult.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/CartRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/CartAddUseCase.kt
Labels: feature 🚀, Iceman 🧊

#119 [FEATURE] Error 발생 시 UiEvent + SharedFlow로 Feedback 제공
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddBottomSheet.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/ErrorDialog.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/UiModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/bottomsheet/BottomSheetViewModel.kt
Labels: feature 🚀, Iceman 🧊

#120 [FEATURE] DataSource 리턴타입이 Flow가 아닌 메서드의 예외처리 방식을 runCatchingErrorEntity로 변경
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/best/BestDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/detail/DetailDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/maindish/MainDishDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/sidedish/SideDishDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/soupdish/SoupDishDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/ApiResponse.kt
Labels: feature 🚀, Iceman 🧊

#122 [FEATURE] Repository의 리턴타입이 Flow가 아닌 메서드의 예외처리 방식을 runCatchingErrorEntity로 변경
  app/src/main/java/co/kr/woowahan_banchan/data/extension/ErrorExtension.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/DetailRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/CartRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/DetailRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/HistoryRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/OrderHistoryRepository.kt
Labels: feature 🚀, Iceman 🧊

#124 [FEATURE] UseCase의 리턴타입이 Flow가 아닌 메서드의 예외처리 방식을 runCatchingErrorEntity로 변경 및 runCatchingErrorEntity 내부 수정
  app/src/main/java/co/kr/woowahan_banchan/data/extension/ErrorExtension.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/HistoryAddUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderDetailUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderListUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderTimeUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/ProductDetailUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/UpdateCartItemsUseCase.kt
Labels: feature 🚀, Iceman 🧊

#127 [FEATURE] Error Handling 로직 세분화 및 Error Propagation 구현
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/best/BestDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/detail/DetailDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/maindish/MainDishDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/sidedish/SideDishDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/soupdish/SoupDishDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/extension/ErrorExtension.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/ApiResponse.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/DetailRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/error/ErrorEntity.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/CartRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/DetailRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/HistoryRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/OrderHistoryRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/CartAddUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/HistoryAddUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderDetailUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderListUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderTimeUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/ProductDetailUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/UpdateCartItemsUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddBottomSheet.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/ErrorDialog.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/UiModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/bottomsheet/BottomSheetViewModel.kt
  app/src/main/res/font/bm_euljiro.otf
  app/src/main/res/font/happiness_sans_bold.otf
  app/src/main/res/font/happiness_sans_regular.otf
  app/src/main/res/layout/dialog_retry.xml
Labels: feature 🚀, Iceman 🧊

#129 [FEATURE] Remote DataSource Test code 작성
  app/build.gradle
  app/src/test/java/co/kr/woowahan_banchan/ExampleUnitTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/api/BestServiceTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/api/DetailServiceTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/api/MainDishServiceTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/api/SideDishServiceTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/api/SoupDishServiceTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/remote/best/BestDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/remote/detail/DetailDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/remote/maindish/MainDishDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/remote/sidedish/SideDishDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/remote/soupdish/SoupDishDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/resource/best_items.json
  app/src/test/java/co/kr/woowahan_banchan/resource/detail_hbbcc.json
  app/src/test/java/co/kr/woowahan_banchan/resource/dishes.json
Labels: feature 🚀, Skipancho 🌮

#130 [FEATURE] CartDataSource 테스트 코드 작성
  app/build.gradle
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImplTest.kt
Labels: feature 🚀, Iceman 🧊

#136 [FEATURE] Repository Flow 예외처리 구현
  app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/CartRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/DishRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/HistoryRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/OrderHistoryRepository.kt
Labels: feature 🚀, Iceman 🧊

#137 [FEATURE] UseCase Flow 예외처리 구현
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetBestsUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetCartItemCountUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetCartItemsUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetDishesUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/LatestOrderTimeUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/RecentlyViewedUseCase.kt
Labels: feature 🚀, Iceman 🧊

#138 [FEATURE] ViewModel Flow 예외처리 구현
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/RecentlyViewedViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/BestViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/MainDishViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/OtherDishViewModel.kt
Labels: feature 🚀, Iceman 🧊

#134 [FEATURE] 9_ProductDetail 화면 Toolbar 추가
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
  app/src/main/res/layout/activity_product_detail.xml
Labels: feature 🚀, Skipancho 🌮

#139 [FEATURE] LocalDataSourceImpl 테스트 코드 작성
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSourceImplTest.kt
Labels: feature 🚀, Iceman 🧊

#142 [FEATURE] CartRepository Test Code 작성
  app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeCartDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeCartDataSourceWithError.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeDetailDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeDetailDataSourceWithError.kt
Labels: feature 🚀, Skipancho 🌮

#144 [FEATURE] DishRepository Test Code 작성
  app/src/test/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeBestDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeMainDishDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeSideDishDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeSoupDishDataSource.kt
Labels: feature 🚀, Skipancho 🌮

#145 [FEATURE] DataSource Flow 예외처리 방식 수정 및 OrderHistoryRepository 테스트 코드 작성
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/FakeOrderDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/FakeOrderItemDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImplTest.kt
Labels: feature 🚀, Iceman 🧊

#146 [FEATURE] OrderHistoryRepository 예외 상황에 대한 테스트 코드 작성
  app/src/test/java/co/kr/woowahan_banchan/data/repository/FakeOrderDataSourceWithError.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/FakeOrderItemDataSourceWithError.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImplTest.kt
Labels: feature 🚀, Iceman 🧊

#149 [REFACTOR] CartDataSource, Result로 에러 타입을 전달하도록 수정
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeCartDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeCartDataSourceWithError.kt
Labels: refactor 🛠, Skipancho 🌮

#148 [MOVE] FakeDataSource 패키지 이동
  app/src/test/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeOrderDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeOrderDataSourceWithError.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeOrderItemDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeOrderItemDataSourceWithError.kt
Labels: feature 🚀, Iceman 🧊

#151 [FEATURE] CartRepository 에러 테스트 코드 작성
  app/src/test/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeBestDataSourceWithError.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeMainDishDataSourceWithError.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeSideDishDataSourceWithError.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeSoupDishDataSourceWithError.kt
Labels: feature 🚀, Skipancho 🌮

#153 [FEATURE] DetailRepository Test Code 작성
  app/src/test/java/co/kr/woowahan_banchan/data/repository/DetailRepositoryImplTest.kt
Labels: feature 🚀, Skipancho 🌮

#154 [FEATURE] HistoryRepository 테스트 코드 작성 및 HistoryDataSource Flow 예외처리 방식 변경
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeHistoryDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeHistoryDataSourceWithError.kt
Labels: feature 🚀, Iceman 🧊

#156 [MOVE] FakeDataSource 패키지 정리
  app/src/test/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/DetailRepositoryImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/local/cart/FakeCartDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/local/cart/FakeCartDataSourceWithError.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/local/history/FakeHistoryDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/local/history/FakeHistoryDataSourceWithError.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/local/order/FakeOrderDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/local/order/FakeOrderDataSourceWithError.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/local/orderitem/FakeOrderItemDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/local/orderitem/FakeOrderItemDataSourceWithError.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/remote/best/FakeBestDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/remote/best/FakeBestDataSourceWithError.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/remote/detail/FakeDetailDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/remote/detail/FakeDetailDataSourceWithError.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/remote/maindish/FakeMainDishDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/remote/maindish/FakeMainDishDataSourceWithError.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/remote/sidedish/FakeSideDishDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/remote/sidedish/FakeSideDishDataSourceWithError.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/remote/soupdish/FakeSoupDishDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/remote/soupdish/FakeSoupDishDataSourceWithError.kt
Labels: chore 🏗, Iceman 🧊

#157 [REFACTOR] testDispatcher 관련 코드 리팩토링
  app/src/test/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImplTest.kt
Labels: refactor 🛠, Iceman 🧊

#163 [FEATURE] ProductDetailActivity UiStates, UiEvents 적용
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
Labels: feature 🚀, Iceman 🧊

#164 [FEATURE] Order Dto Column 추가 및 Room DataBase Migration
  app/build.gradle
  app/src/main/java/co/kr/woowahan_banchan/data/database/BanchanDatabase.kt
  app/src/main/java/co/kr/woowahan_banchan/data/database/Migration.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/local/OrderDto.kt
  app/src/main/java/co/kr/woowahan_banchan/data/model/local/OrderItemDto.kt
  app/src/main/java/co/kr/woowahan_banchan/di/DatabaseModule.kt
Labels: feature 🚀, Skipancho 🌮

#165 [FEATURE] OrderListFragment UiStates, UiEvents 적용
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderlist/OrderListFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderListViewModel.kt
Labels: feature 🚀, Iceman 🧊

#167 [FEATURE] ImageLoader 개선 및 PlaceHolder 구현
  app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DetailDataResponse.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/CartAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/DishAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/ProductDetailViewPagerAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/RecentlyViewedAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddBottomSheet.kt
  app/src/main/java/co/kr/woowahan_banchan/util/ImageLoader.kt
Labels: feature 🚀, Skipancho 🌮

#169 [REFACTOR] Migration 을 DataBase 클래스 내부로 이동
  app/src/main/java/co/kr/woowahan_banchan/data/database/BanchanDatabase.kt
  app/src/main/java/co/kr/woowahan_banchan/data/database/Migration.kt
  app/src/main/java/co/kr/woowahan_banchan/di/DatabaseModule.kt
Labels: refactor 🛠, Skipancho 🌮

#171 [FEATURE] OrderDetailFragment UiStates, UiEvents 적용
  app/.gitignore
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderDetailViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
Labels: feature 🚀, Iceman 🧊

#173 [FEATURE] HistoryFragment UiStates, UiEvents 적용
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/HistoryUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/history/HistoryFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/HistoryViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/RecentlyViewedViewModel.kt
  app/src/main/res/layout/fragment_history.xml
Labels: feature 🚀, Iceman 🧊

#174 [FEATURE] 주문 완료 정보 불러오기 구현
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/CheckOrderCompleteUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
Labels: feature 🚀, Skipancho 🌮

#176 [FEATURE] BestFragment UiStates, UiEvents 적용
  app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/history/HistoryFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/ErrorDialog.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/BestViewModel.kt
Labels: feature 🚀, Iceman 🧊

#179 [FEATURE] MainDishFragment UiStates, UiEvents 적용
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/MainDishViewModel.kt
Labels: feature 🚀, Iceman 🧊

#178 [FEATURE] 주문 완료 업데이트 기능 구현
  app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderDao.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSource.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/repository/OrderHistoryRepository.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/usecase/UpdateOrderUseCase.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/notification/AlarmReceiver.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/worker/OrderUpdateWorker.kt
Labels: feature 🚀, Skipancho 🌮

#181 [FEATURE] OtherDishFragment UiStates, UiEvents 적용
  app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/OtherDishViewModel.kt
  app/src/main/res/layout/fragment_other_dish.xml
Labels: feature 🚀, Iceman 🧊

#183 [FEATURE] CartAddBottomSheet UiStates, UiEvents 적용
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddBottomSheet.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/bottomsheet/BottomSheetViewModel.kt
Labels: feature 🚀, Iceman 🧊

#185 [FEATURE] CartActivity, OrderActivity 기기 회전 대응
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/OrderActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
Labels: feature 🚀, Skipancho 🌮

#190 [FEATURE] OrderDao, OrderDataSource, OrderRepository 변경에 따른 Test Code 추가
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/remote/best/BestDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/remote/detail/DetailDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/remote/maindish/MainDishDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/remote/sidedish/SideDishDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/datasource/remote/soupdish/SoupDishDataSourceImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImplTest.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/local/order/FakeOrderDataSource.kt
  app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/local/order/FakeOrderDataSourceWithError.kt
Labels: feature 🚀, Skipancho 🌮

#188 [FEATURE] CartFragment UiStates, UiEvents 적용
  app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/UiState.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
Labels: feature 🚀, Iceman 🧊

#193 [RENAME] UiStates -> UiState, UiEvents -> UiEvent 클래스명 수정
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/history/HistoryFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderlist/OrderListFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddBottomSheet.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/UiModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/bottomsheet/BottomSheetViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/HistoryViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/BestViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/MainDishViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/OtherDishViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderDetailViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderListViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
Labels: refactor 🛠, Iceman 🧊

#191 [FEATURE] 데모 및 시연을 위한 배송 완료까지 걸리는 시간 20분 -> 10초 변경
  app/src/main/java/co/kr/woowahan_banchan/data/model/local/OrderDto.kt
  app/src/main/java/co/kr/woowahan_banchan/domain/entity/orderhistory/OrderHistory.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/util/NumberExtension.kt
Labels: feature 🚀, Iceman 🧊

#196 [FEATURE] 빌드 및 Release 자동화
  .github/workflows/auto_release.yml
  CHANGELOG.md
  app/src/test/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImplTest.kt
Labels: feature 🚀, Skipancho 🌮

#198 [HOTFIX] #197 - 배송완료 시간 관련 Hotfix
  CHANGELOG.md
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/util/NumberExtension.kt
Labels: bug 🐛, Pair Programming 🤝

#207 [FIX] 카트 개수가 10개 이상이 되면 9+가 되도록 수정
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
Labels: bug 🐛, Skipancho 🌮

#208 [FIX] 장바구니 화면에서 최근 본 화면으로 넘어가 장바구니를 추가하게 되면 주문이 중복되는 오류 수정
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
Labels: bug 🐛, Skipancho 🌮

#210 [FIX] 네트워크 연결 해제 상태에서 에러 다이얼로그가 여러 번 표시되는 오류
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/BestViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/MainDishViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/OtherDishViewModel.kt
  app/src/main/java/co/kr/woowahan_banchan/util/ImageLoader.kt
Labels: bug 🐛, Iceman 🧊

#209 [FIX] 카트버튼 이벤트 누락 수정
  app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/DishAdapter.kt
Labels: bug 🐛, Skipancho 🌮

#211 [FIX] 장바구니 화면에서 주문 후 화면 회전 시 화면 유지되지 않는 오류
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartActivity.kt
  app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
Labels: bug 🐛, Iceman 🧊

#214 [FEATURE] #213 - ImageLoader 의 캐시를 HashMap에서 LruCache로 변경
  app/src/main/java/co/kr/woowahan_banchan/util/ImageLoader.kt
Labels: feature 🚀, Skipancho 🌮

#212 [REFACTOR] Hilt @Binds, @Provides 리팩토링
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/best/BestDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/detail/DetailDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/maindish/MainDishDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/sidedish/SideDishDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/soupdish/SoupDishDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_banchan/di/ApiModule.kt
  app/src/main/java/co/kr/woowahan_banchan/di/DataSourceModule.kt
  app/src/main/java/co/kr/woowahan_banchan/di/RepositoryModule.kt
  app/src/main/res/layout/activity_product_detail.xml
Labels: refactor 🛠, Iceman 🧊
